repos:
  # # C/C++
  # - repo: https://github.com/pre-commit/mirrors-clang-format
  #   rev: v16.0.6
  #   hooks:
  #     - id: clang-format
  #       files: \.(cpp|hpp|c|h)$

  # # CMake
  # - repo: https://github.com/cheshirekow/cmake_format
  #   rev: v0.6.13
  #   hooks:
  #     - id: cmake-format
  #       files: CMakeLists\.txt$|\.cmake$

  # # Shell scripts & Makefiles
  # - repo: https://github.com/scop/pre-commit-shfmt
  #   rev: v3.11.0-1            # or pin to whatever tag you prefer
  #   hooks:
  #     - id: shfmt             # uses the upstream prebuilt binary
  #       args: ["-i", "2", "-ci"]

  # # Dockerfiles
  # - repo: https://github.com/hadolint/hadolint
  #   rev: v2.12.0
  #   hooks:
  #     - id: hadolint
  #       files: Dockerfile

  # Python (Ruff)
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.11.8
    hooks:
      - id: ruff
        args:
          - --config=pyproject.toml
          - --fix