version: "3.9"

services:
  trt:
    build:
      context: .
      dockerfile: docker/trt.Dockerfile
    image: turbo-rank-trt:latest
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ./models:/workspace/turbo-rank/models:ro
    ports:
      - "50051:50051"
    healthcheck:
      test: ["CMD", "grpc-health-probe", "-addr=localhost:50051", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  ort:
    build:
      context: .
      dockerfile: docker/ort.Dockerfile
    image: turbo-rank-ort:latest
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ./models:/workspace/turbo-rank/models:ro
    ports:
      - "50052:50051"   # avoid port clash
    healthcheck:
      test: ["CMD", "grpc-health-probe", "-addr=localhost:50051", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s