version: "3.9"

services:
  trt:
    build:
      context: .
      dockerfile: docker/trt.Dockerfile
    image: turbo-rank-trt:latest
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ./models:/workspace/turbo-rank/models:ro
    ports:
      - "50051:50051"
    # keep container alive
    command: ["bash", "-c", "while true; do sleep 3600; done"]
    # interactive shell you can also add:
    stdin_open: true
    tty: true


  ort:
    build:
      context: .
      dockerfile: docker/ort.Dockerfile
    image: turbo-rank-ort:latest
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ./models:/workspace/turbo-rank/models:ro
    ports:
      - "50052:50051"   # avoid port clash
    # keep container alive
    command: ["bash", "-c", "while true; do sleep 3600; done"]
    # interactive shell you can also add:
    stdin_open: true
    tty: true